# Run installation checks

name: pca-check

on:
  push:
    branches:
      - main
    paths:
      - gwaspy/pca/**

jobs:
  install:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install GWASpy
      run: |
        python setup.py sdist
        pip install dist/GWASpy-0.1.0.tar.gz
    - name: Check modules
      run: |
        preimp_qc --help
        pca --help
        imputation --help
    - name: PCA Run Test
      run: |
        pca --dirname data/ --basename 1kg_annotated --out-dir data/ --input-type hail --reference grch37
